sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t tetianafilonenko/multi-client ./client
  - docker build -t tetianafilonenko/multi-server ./server
  - docker build -t tetianafilonenko/multi-nginx ./nginx
  - docker build -t tetianafilonenko/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push tetianafilonenko/multi-client
  - docker push tetianafilonenko/multi-server
  - docker push tetianafilonenko/multi-nginx
  - docker push tetianafilonenko/multi-worker
